# Generated by Django 2.2.19 on 2024-04-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
